### ISSUE TITLE
add category

### ISSUE THREAD

**Issue by darom90** [pnc-virtual-company/2020-G3-letsgo#29]
add category to database
condition if category already in database will show alert message "category already exist"

**Comment by ronanpnc** [comment]
@puthyrakheng   just a test to check customer mail

**Comment by puthyrakheng** [comment]
Hello !! Yes .. everthing is okay

**Comment by sovonthy** [comment]
@sengseiha-sam  Good morning teacher I have completed add category and condition if category already exist cant't add. Please check it for me.
