### ISSUE TITLE
Design all database table

### ISSUE THREAD

**Issue by sovonthy** [pnc-virtual-company/2020-G3-letsgo#3]
Design table database have:
-user
-cities
-event
-categories

+ user:
  -firstname
  -lastname
  -email
  -password
  -picture
  -role

+ cities
  -name

+ event
  -title
  -start date
  -end date
  -time
  -picture
  -description

+ categories
  -name

**Comment by ronanpnc** [comment]
this is  not an improvement => it 's a docuementation issue

**Comment by sovonthy** [comment]
@ronanpnc Thank you teacher for remark
